server:
  port: 8080
  servlet:
    context-path: /api/${api.version}
  name: iCanDo
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    accept-count: 200
    connection-timeout: 20000
api:
  version: v1

swagger:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:8080/api/v1}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPENAI_API_KEY}

cloud:
  aws:
    s3:
      bucketName: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
