INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '가장 좋아하는 영화나 드라마는 뭐예요? (인생 영화/드라마)');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '요즘 가장 즐겨 듣는 노래가 있나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '좋아하는 음악 장르나 가수가 있다면?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '인생 책이나 웹툰을 꼽는다면?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '가장 좋아하는 음식과 싫어하는 음식은?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '민트초코 좋아하세요? (민초파 vs 반민초파)');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '파인애플 피자에 대한 생각은? (하와이안 피자 호 vs 불호)');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '가장 기억에 남는 여행지는 어디였나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '학창 시절 가장 재미있었던 추억은?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '어릴 적 꿈은 무엇이었나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '처음으로 아르바이트했던 경험 이야기');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '최근에 새로 알게 된 놀라운 사실이 있다면?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '잊을 수 없는 선생님이나 멘토가 있나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '주말이나 쉬는 날에는 보통 무얼 하며 보내세요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '요즘 새롭게 빠져있는 취미가 있나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '스트레스는 어떻게 푸는 편인가요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '집순이/집돌이 vs 밖에서 활동하는 타입?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '즐겨 하는 운동이 있나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '산 vs 바다, 어디를 더 좋아하세요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '무언가를 수집해 본 경험이 있나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '로또 1등에 당첨된다면 가장 먼저 하고 싶은 일은?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '무인도에 딱 3가지만 가져갈 수 있다면?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '꼭 한번 만나보고 싶은 역사 속 인물이나 유명인이 있나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '가방에 꼭 챙겨 다니는 필수템 3가지');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '외계인이나 귀신의 존재를 믿으시나요?');
INSERT INTO topic (category, topic) VALUES ('DAILY_LIFE', '전화 통화 vs 문자 메시지, 어떤 걸 더 편하게 느끼나요?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', 'AI가 내 일자리를 대체할 수 있을까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', 'SNS는 우리 삶에 긍정적인 영향을 더 많이 줄까, 부정적인 영향을 더 많이 줄까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '미래에는 현금 없는 사회가 될까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '주 4일 근무제 도입에 대해 어떻게 생각하는가?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '평생직장과 잦은 이직, 어떤 커리어가 더 바람직할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '로또 1등에 당첨된다면, 하던 일을 계속할 것인가?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '배달앱 수수료, 이대로 괜찮은가?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '유튜브, 넷플릭스 등 OTT 서비스, 우리 삶을 어떻게 바꾸었나?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '1인 미디어(유튜버, BJ)는 언론인이라고 볼 수 있을까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '층간소음 문제, 어떻게 해결해야 할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '명절 문화, 어떻게 바뀌어야 할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '투표 연령, 더 낮춰야 할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '사형제는 폐지되어야 할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '간접흡연, 강력한 규제가 더 필요할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', 'CCTV 확대, 안전을 위해 사생활 침해를 감수할 수 있나?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '인터넷 실명제 도입에 찬성하는가, 반대하는가?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '우리나라 교육의 가장 큰 문제점은 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '조기 교육은 아이에게 꼭 필요할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '수능, 이대로 괜찮은가? 대안은 없을까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '대학은 꼭 가야 할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '학교 내 체벌, 어떤 경우에도 허용되어서는 안 될까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '우리나라 학생들이 가장 행복해지려면 무엇이 바뀌어야 할까?');
INSERT INTO topic (category, topic) VALUES ('SOCIAL_POLITICS', '대학 서열화 현상에 대해 어떻게 생각하는가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '나만의 ''짠테크''나 절약 노하우가 있다면?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '주식 vs 부동산, 2025년 지금 더 매력적인 투자처는?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '은행 예·적금만으로 자산을 불리는 시대는 끝났을까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '자녀에게 경제 교육은 언제, 어떻게 시작해야 할까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '신용카드 vs 체크카드, 나의 주력 카드는? 그 이유는?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '가상화폐(암호화폐), 신뢰할 수 있는 투자 자산일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '연금(국민연금, 개인연금), 나의 노후를 책임져 줄 수 있을까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''더치페이''와 ''한턱내기'' 문화, 어떤 게 더 합리적일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '보험, 꼭 필요한 최소한의 종류는 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '로또 1등에 당첨된다면, 자산 관리는 어떻게 할 것인가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '배달앱 없이 못 사는 시대, 배달비는 얼마까지 적당할까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''한정판'' 마케팅에 끌리는 이유는 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '내가 가장 충성도 높은 브랜드는 무엇인가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '광고가 소비에 얼마나 영향을 미친다고 생각하는가');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''오늘의 집'' 처럼 콘텐츠와 커머스를 결합한 플랫폼을 이용해 본 적 있나?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''알뜰폰''으로 바꾸지 않는 이유는 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '무인 점포(아이스크림 가게, 카페 등), 이용해 보니 어떤가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '대기업과 스타트업, 나의 성향에 더 맞는 곳은?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''이직''은 성장을 위한 필수 과정일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''평생 직업''을 갖기 위해 지금 준비해야 할 것은?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '회사 복지 중 가장 중요하다고 생각하는 것은? (워라밸, 보상, 성장 기회 등)');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '상사의 ''꼰대'' 성향과 부하 직원의 ''MZ'' 성향, 누가 더 변해야 할까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '점심시간 1시간, 나만의 활용법은?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '회식은 꼭 필요한 조직 문화일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', 'CEO가 된다면, 가장 먼저 바꾸고 싶은 회사 정책은?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '대기업의 문어발식 확장, 어떻게 생각하는가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '프랜차이즈 창업, 안정적인 선택일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''골목상권''을 살리기 위한 가장 좋은 방법은 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', 'AI 기술을 가장 잘 활용하고 있는 국내 기업은 어디라고 생각하는가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '헬스케어 산업의 미래는 어떤 모습일까? (원격 진료, AI 진단 등)');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '현금 없는 사회, 장단점은 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '최저임금 인상, 경제에 긍정적일까 부정적일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''상속세'', 이대로 유지해야 할까? 개편해야 할까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''실업급여'', 이대로 괜찮은가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''주 52시간 근무제''는 잘 지켜지고 있을까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '경제적으로 ''성공한 삶''이란 무엇이라고 생각하는가?');
INSERT INTO topic (category,topic) VALUES ('ECONOMY_BUSINESS', '''부자''들의 소비 습관 중 따라 하고 싶은 것이 있다면?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '경제 뉴스, 꼭 챙겨 봐야 할까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''빚''도 자산이라는 말에 동의하는가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '어릴 때 받은 용돈이 경제 관념에 영향을 미쳤을까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', ' ''돈으로 행복을 살 수 없다는 말'', 어떻게 생각하는가?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '내가 생각하는 ''가성비'' 최고의 물건이나 서비스는?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''취미''에 한 달에 얼마까지 쓸 수 있나?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''무료'' 서비스는 정말 공짜일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '돈 관리를 잘하는 사람들의 공통점은 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '''복권''을 사는 것은 합리적인 행동일까?');
INSERT INTO topic (category, topic) VALUES ('ECONOMY_BUSINESS', '경제/경영 분야에서 당신의 롤모델이 있다면?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', 'AI가 나의 일자리를 대체할 수 있다는 불안감을 느끼는가?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', 'AI 면접관이 나를 평가한다면, 공정하다고 느낄까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', 'AI가 특정 인종이나 성별을 차별하는 결정을 내린다면 책임은 누구에게 있을까? (개발자 vs 사용자 vs AI)');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', 'AI 시대에 인간에게 가장 필요한 능력은 무엇일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '인간의 수명이 150세까지 늘어난다면, 우리 사회는 어떻게 변할까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '뇌에 칩을 심어 지능을 높이거나 외국어를 즉시 배우는 기술, 사용하겠는가?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '모든 질병을 사전에 예측하고 예방하는 세상이 온다면?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '노화(Aging)는 질병일까, 자연스러운 현상일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '정신적 고통이나 트라우마를 약물로 치료하는 미래, 어떻게 생각하는가?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '나의 모든 유전자 정보가 공개되는 것에 동의할 수 있는가?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '우주 엘리베이터는 실현 가능한 기술일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '우주에서 태어난 첫 번째 아기는 어느 나라 국민일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '우주 개발에 천문학적인 비용을 투자하는 것, 과연 가치 있는 일일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '가상현실(VR)과 증강현실(AR)이 일상화된 미래는 어떤 모습일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '''메타버스''에서 일하고, 쇼핑하고, 친구를 만나는 것이 현실 세계를 대체할 수 있을까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '자율주행차가 완벽해진다면, 운전면허는 사라질까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '모든 것을 빌려 쓰는 ''구독 경제''와 ''공유 경제''가 더 확산될까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '개인의 모든 행동이 데이터로 기록되는 ''빅데이터 사회'', 편리할까 감시 사회일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '미래에는 국가의 경계가 희미해질까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '스마트폰을 대체할 차세대 기기는 어떤 모습일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '6G 시대가 열리면 우리 삶은 어떻게 달라질까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '재택근무, 원격근무가 미래의 표준적인 업무 형태가 될까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '미래의 교육은 학교가 아닌 온라인에서 이루어질까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '3D 프린터로 음식, 옷, 생필품을 만들어 쓰는 시대가 올까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '해상 도시, 지하 도시 등 미래의 주거 형태는 어떻게 변할까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '실시간 통역 기술의 발전으로 외국어 공부가 필요 없어질까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '1인 미디어가 전통 언론을 완전히 대체하는 날이 올까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '기술 발전으로 더 여유로워진 시간을 어떻게 보내고 싶은가?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '인간의 뇌와 컴퓨터를 연결하는 기술, 인류에게 축복일까 재앙일까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '가상 세계에서의 범죄는 현실 세계와 동일하게 처벌해야 할까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '과학 기술자에게 더 높은 수준의 윤리 의식이 요구되어야 할까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '기술 발전의 최종 목표는 무엇이어야 할까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '해수면 상승으로 사라질 위기에 처한 나라들, 기술로 구할 수 있을까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '인공 강우 기술을 적극적으로 사용해도 괜찮을까?');
INSERT INTO topic (category, topic) VALUES ('TECH_FUTURE', '기술 발전과 환경 보호, 두 가지 가치는 양립할 수 있을까?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '최근에 가장 인상 깊게 읽은 책은 무엇인가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '전자책(e-book)과 종이책, 각각의 매력은 무엇이라고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '웹툰, 웹소설은 새로운 문학 장르가 될 수 있을까요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '베스트셀러는 꼭 읽어봐야 한다고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '책을 고르실 때, 작가, 제목, 표지, 추천사 중 무엇을 가장 먼저 보시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '동네 서점과 대형 서점 중 어떤 공간을 더 선호하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '''독서''가 최고의 취미라는 말에 동의하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '책에 밑줄을 긋거나 메모를 하면서 읽는 편이신가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '여러 책을 동시에 읽는 것과 한 권을 끝내고 다음 책을 읽는 것 중 어떤 스타일이신가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '자신만의 서재에 대한 로망이 있으신가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '어린 시절 읽었던 동화책 중 가장 기억에 남는 작품은 무엇인가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '공공장소에 설치된 미술 작품(공공 미술)에 관심을 가져본 적이 있으신가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '사진이 그림을 대체할 수 있다고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '캐릭터 굿즈(인형, 스티커 등)를 사 모으는 이유는 무엇이라고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '폰트(글씨체)가 전체적인 디자인 인상에 얼마나 영향을 미친다고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '''색깔''이 기분이나 감정에 미치는 영향이 있다고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '뮤지컬, 연극, 콘서트 등 직접 관람하는 공연의 가장 큰 매력은 무엇인가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '스탠드업 코미디나 토크 콘서트에 가보신 적이 있으신가요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '박물관은 지루한 곳이라는 편견을 어떻게 깰 수 있을까요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '무명 예술가에 대한 정부나 사회의 지원은 어느 정도까지 필요하다고 보시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '예술가에게 영감을 주는 것은 무엇이라고 생각하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '예술 교육(음악, 미술 등)은 모든 학생에게 필수적일까요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '모방은 창조의 어머니라는 말에 동의하시나요?');
INSERT INTO topic (category, topic) VALUES ('CULTURE_ARTS', '대중의 비판 때문에 준비하던 작품의 내용이 바뀌는 현상은 바람직하다고 생각하시나요?');
